server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost/ecommerce
    username: root
    password: 123456
  profiles:
    active: dev

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

    hibernate:
      ddl-auto: update

ecommerce:
  security:
    secret: '218FA06256311F58BD8BB1E5D8963A44238FDA330AB40EAAEB26BEA2C956B9B5'
    expiration: '3600000'