server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost/ecommerce
    username: root
    password: 123456

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

    hibernate:
      ddl-auto: update